#ifndef NFCSCANNER_VERSION
#define NFCSCANNER_VERSION "0.0.0+unknown.manual"
#endif

#define STR(s) __STR(s)
#define __STR(s) #s

#define SS -1

#include <ArduinoHttpClient.h>
#include <URLParser.h>

#include <ArduinoJson.h>

#include <Electroniccats_PN7150.h>
#undef ERROR
#include <Wire.h>

#include <Adafruit_NeoPixel.h>

#include "util.h"
#include "networking.h"


#define PN7150_WIRE (Wire1)
#define PN7150_IRQ (uint8_t)(9)
#define PN7150_VEN (uint8_t)(12)
#define PN7150_ADDR (uint8_t)(0x28)

bool DEBUG_MODE = false;

Electroniccats_PN7150 nfc(PN7150_IRQ, PN7150_VEN, PN7150_ADDR, &PN7150_WIRE);
void displayCardInfo();

// D13 (GP8) = carrier board
// GP14 = challenger
Adafruit_NeoPixel neopixel(1, 8, NEO_GRB + NEO_KHZ800);




auto url = ParsedUrl("https://eventaccess.uhx.no/api/nfctag");

HttpClient http = HttpClient(client, url.host(), url.port());

IPAddress my_ip;

void setup() {
  http.kUserAgent = "NFCScanner/" STR(NFCSCANNER_VERSION);

  neopixel.begin();
  neopixel.setBrightness(50);

  neopixel.clear();
  neopixel.show();
  delay(10);

  neopixel.fill(neopixel.Color(100, 0, 0));
  neopixel.show();


  // start serial port:
  Serial.begin(115200);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
    // TODO: Should not block waiting for serial in production
    //       Time out after a few seconds
  }

  neopixel.fill(neopixel.Color(100, 50, 0));
  neopixel.show();

  Serial.println("NFCScanner v" STR(NFCSCANNER_VERSION));

  networking_setup();

  // give the Ethernet shield a second to initialize:
  delay(1000);
  Serial.println();

  http.setHttpWaitForDataDelay(10);
  setTimeout(200);

  neopixel.fill(neopixel.Color(100, 100, 0));
  neopixel.show();

  Serial.println("Detect NFC tags with PN7150");

  Serial.println("Initializing...");
  pinMode(PN7150_IRQ, INPUT);

  if (nfc.connectNCI()) {  // Wake up the board
    Serial.println("Error while setting up the mode, check connections!");
    while (1)
      ;
  }

  if (nfc.configureSettings()) {
    Serial.println("The Configure Settings is failed!");
    while (1)
      ;
  }

  // Read/Write mode as default
  if (nfc.configMode()) {  // Set up the configuration mode
    Serial.println("The Configure Mode is failed!!");
    while (1)
      ;
  }
  nfc.startDiscovery();  // NCI Discovery mode
  Serial.println("Waiting for an Card ...");

  neopixel.fill(neopixel.Color(0, 100, 0));
  neopixel.show();
}

enum TagValidity {
  ERROR=100,
  INVALID=0,
  VALID=1,
};

// Needed because TagValidity does not exist when Arduino's autogenerated prototypes are added
TagValidity checkTag(const char* tag_id);

TagValidity checkTag(const char* tag_id) {
  /* Attempting to perform a HTTP request while link is disconnected causes a 60s delay
  */
  // TODO: Reimplement
  //if (Ethernet.linkStatus() == EthernetLinkStatus::LinkOFF) {
  //  Serial.println("Error: Ethernet cable not connected");
  //  return TagValidity::ERROR;
  //}

  String nfc_url = url.path();
  nfc_url += "/";
  nfc_url += tag_id;
  Serial.println(http.httpResponseTimeout());
  Serial.println(http.httpWaitForDataDelay());
  Serial.println(http.getTimeout());

  http.beginRequest();
  http.post(nfc_url);
  http.endRequest();

  // read the status code and body of the response
  int statusCode = http.responseStatusCode();
  String response = http.responseBody();

  Serial.print("Status code: ");
  Serial.println(statusCode);
  Serial.print("Response: ");
  Serial.println(response);

  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, response);

  if (err) {
    Serial.print(F("Deserializing JSON failed: "));
    Serial.println(err.c_str());
  }

  if (doc["error"].is<const char*>()) {
    Serial.print("API returned error message: ");
    Serial.println(doc["error"].as<const char*>());
  }

  if (doc["valid"].is<bool>()) {
    if (doc["valid"].as<bool>()) {
      tone(D5, 2093, 250);
      Serial.println("Valid tag!");
      return TagValidity::VALID;
    } else {
      tone(D5, 523, 100);
      delay(150);
      tone(D5, 523, 100);
      delay(150);
      Serial.println("Invalid tag!!!");
      return TagValidity::INVALID;
    }
  } else {
    tone(D5, 523, 100);
    delay(150);
    tone(D5, 523, 100);
    delay(150);
    tone(D5, 523, 100);
    delay(150);
    tone(D5, 523, 100);
    Serial.println("Invalid tag!!!");
    Serial.println("Key valid either isn't bool or does not exist.");
  }

  Serial.println("Error occured!");

  return TagValidity::ERROR;
}

void setTimeout(uint16_t timeout) {
  //ethernet.setTimeout(timeout);
  //ethernet.setConnectionTimeout(timeout);
  http.setTimeout(timeout);

  http.setHttpResponseTimeout(2*timeout);
}

void loop() {
  //ethernet_maintain();
  networking_loop();


  //Serial.print("HTTP Remote: ");
  //Serial.print(http.iServerAddress);

  // TODO: Reconnect on connection failure
  //       Both the Ethernet link, and the TCP socket
  //Serial.println("making POST request");

  //checkTag("deadbeef");

  //Serial.println("-----");
  //Serial.flush();


  // TODO: Currently waits out the timeout, fails, resets and *then* detects the tag
  if (nfc.isTagDetected(500)) {
    neopixel.fill(neopixel.Color(0, 0, 100));
    neopixel.show();

    displayCardInfo();

    // It can detect multiple cards at the same time if they use the same protocol
    if (nfc.remoteDevice.hasMoreTags()) {
      nfc.activateNextTagDiscovery();
      Serial.println("Multiple cards are detected!");
    }

    Serial.println("Remove the Card");
    nfc.waitForTagRemoval();
    Serial.println("Card removed!");

    neopixel.clear();
    neopixel.show();
  } else {

    neopixel.fill(neopixel.Color(100, 0, 0));
    neopixel.show();
  }

  //Serial.println("Restarting...");
  nfc.reset();
  //Serial.println("Waiting for a Card...");
  //delay(500);

  neopixel.fill(neopixel.Color(0, 100, 0));
  neopixel.show();
}

void displayCardInfo() {  // Funtion in charge to show the card/s in te field
  char tmp[16];

  while (true) {
    switch (nfc.remoteDevice.getProtocol()) {  // Indetify card protocol
      case nfc.protocol.T1T:
      case nfc.protocol.T2T:
      case nfc.protocol.T3T:
      case nfc.protocol.ISODEP:
        Serial.print(" - POLL MODE: Remote activated tag type: ");
        Serial.println(nfc.remoteDevice.getProtocol());
        break;
      case nfc.protocol.ISO15693:
        Serial.println(" - POLL MODE: Remote ISO15693 card activated");
        break;
      case nfc.protocol.MIFARE:
        Serial.println(" - POLL MODE: Remote MIFARE card activated");
        break;
      default:
        Serial.println(" - POLL MODE: Undetermined target");
        return;
    }

    String nfc_id = "";
    TagValidity is_ok;

    switch (nfc.remoteDevice.getModeTech()) {  // Indetify card technology
      case (nfc.tech.PASSIVE_NFCA):
        Serial.println("\tTechnology: NFC-A");
        Serial.print("\tSENS RES = ");
        Serial.println(getHexRepresentation(nfc.remoteDevice.getSensRes(), nfc.remoteDevice.getSensResLen()));

        Serial.print("\tNFC ID = ");
        Serial.println(getHexRepresentation(nfc.remoteDevice.getNFCID(), nfc.remoteDevice.getNFCIDLen()));
        nfc_id = getHexRepresentation(nfc.remoteDevice.getNFCID(), nfc.remoteDevice.getNFCIDLen(), "", "");
        Serial.println(nfc_id);

        Serial.print("\tSEL RES = ");
        Serial.println(getHexRepresentation(nfc.remoteDevice.getSelRes(), nfc.remoteDevice.getSelResLen()));

        is_ok = checkTag(nfc_id.c_str());

        switch (is_ok) {
          case (TagValidity::VALID):
            Serial.println("\tBackend validated tag as OK");
            break;
          case (TagValidity::INVALID):
            Serial.println("\tBackend validated tag as REJECTED");
            break;
          case (TagValidity::ERROR):
            Serial.println("\tBackend validation failed with ERROR");
            break;
        }

        break;

      case (nfc.tech.PASSIVE_NFCB):
      case (nfc.tech.PASSIVE_NFCF):
      case (nfc.tech.PASSIVE_NFCV):
      default:
        break;
    }

    // It can detect multiple cards at the same time if they are the same technology
    if (nfc.remoteDevice.hasMoreTags()) {
      Serial.println("Multiple cards are detected!");
      if (!nfc.activateNextTagDiscovery()) {
        break;  // Can't activate next tag
      }
    } else {
      break;
    }
  }
}
